# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Compile Lint Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install
        run: |
          yarn global add node-gyp-cache
          yarn config set node_gyp node-gyp-cache
          yarn install --frozen-lockfile
      - name: Compile
        run: yarn compile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
